// <auto-generated />
using System;
using LarpCharacterBuilder3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LarpCharacterBuilder3.Migrations
{
    [DbContext(typeof(LarpBuilderContext))]
    [Migration("20200620235838_CharacterEvent")]
    partial class CharacterEvent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("TotalCp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.CharacterEvent", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CharacterId1")
                        .HasColumnType("int");

                    b.Property<int?>("EventId1")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "EventId");

                    b.HasIndex("CharacterId1");

                    b.HasIndex("EventId1");

                    b.ToTable("CharacterEvents");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.CharacterSkill", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CharacterId1")
                        .HasColumnType("int");

                    b.Property<int?>("SkillId1")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("CharacterId1");

                    b.HasIndex("SkillId1");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.CharacterEvent", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Character", "Character")
                        .WithMany("CharacterEvents")
                        .HasForeignKey("CharacterId1");

                    b.HasOne("LarpCharacterBuilder3.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId1");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.CharacterSkill", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("CharacterId1");

                    b.HasOne("LarpCharacterBuilder3.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId1");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Event", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Skill", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Skill", null)
                        .WithMany("Children")
                        .HasForeignKey("SkillId");
                });
#pragma warning restore 612, 618
        }
    }
}
