// <auto-generated />
using System;
using LarpCharacterBuilder3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LarpCharacterBuilder3.Migrations
{
    [DbContext(typeof(LarpBuilderContext))]
    [Migration("20200609152448_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("TotalCp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.CharacterEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharactersId");

                    b.HasIndex("EventId");

                    b.ToTable("CharacterEvent");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SkillId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.CharacterEvent", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Character", "Characters")
                        .WithMany("CharacterEvents")
                        .HasForeignKey("CharactersId");

                    b.HasOne("LarpCharacterBuilder3.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Event", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("LarpCharacterBuilder3.Models.Skill", b =>
                {
                    b.HasOne("LarpCharacterBuilder3.Models.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId");

                    b.HasOne("LarpCharacterBuilder3.Models.Skill", null)
                        .WithMany("Children")
                        .HasForeignKey("SkillId");
                });
#pragma warning restore 612, 618
        }
    }
}
